---
title: "Easy way to parallel processing in R"
author: "Koji MAKIYAMA"
output:
  html_document:
    keep_md: yes
---

```{r echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE)
```

## Overture

There is a parallel processing code using the `foreach` package:

```{r}
library(doParallel)
cl <- makeCluster(detectCores())
registerDoParallel(cl)
result <- foreach(i = 1:3, .combine=c) %dopar% {
  i**2
}
stopCluster(cl)
print(result)
```

It can be simplified using `pforeach()` instead of `foreach()`:

```{r}
library(pforeach)
result <- pforeach(i = 1:3)({
  i**2
})
print(result)
```

## How to install

```{r, eval=FALSE}
install.packages("devtools") # if you have not installed "devtools" package
devtools::install_github("hoxo-m/pforeach")
```

## To simplify!

### With other packages

Using `foreach()`:

```{r}
library(doParallel)
library(dplyr) # With other package
cl <- makeCluster(detectCores())
registerDoParallel(cl)
# You must indicate .packages parameter.
result <- foreach(i = 1:3, .combine=c, .packages="dplyr") %dopar% {
  iris[i, ] %>% select(-Species) %>% sum
}
stopCluster(cl)
print(result)
```

Using `pforeach()`:

```{r}
library(pforeach)
library(dplyr) # With other package
# You need not to mind that.
pforeach(i = 1:3)({
  iris[i, ] %>% select(-Species) %>% sum
})
```

### With enclosed variables

Using `foreach()`:

```{r}
# You must indicate .export parameter. 
square <- function(x) x**2
execute <- function() {
  cl <- makeCluster(detectCores())
  registerDoParallel(cl)
  result <- foreach(i = 1:3, .combine=c, .export="square") %dopar% {
    square(i)
  }
  stopCluster(cl)
  result
}
execute()
```

Using `pforeach()`:

```{r}
# Need not to mind!
library(pforeach)
square <- function(x) x**2
execute <- function() {
  pforeach(i = 1:3)({
    square(i)
  })
}
execute()
```

### Row and Column

## Options

### Cores

### Fix random seed

### Do not parallel
